baseURL: 'https://ne1atonin.github.io/'
languageCode: 'en'
theme: "DoIt"
author: 
  name: "~Asha/Herro"
title: '~Asha/Herro'
copyright: "All Rights Reserved"
IsMultiLingual: true
defaultContentLanguage: en

languages:
  en:
    weight: 1
    languageName: "English"
    menu: 
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts" 
          weight: 1
        - identifier: "writeups"
          name: "Writeups"
          url: "/writeups"
          weight: 2
        - identifier: "tools and resources"
          name: "Tools and Resources"
          url: "/resources"
          weight: 3
        - identifier: "tryhackme"
          name: "TryHackMe"
          url: "/tryhackme"
          parent: "writeups"
        - identifier: "hackthebox"
          name: "HackTheBox"
          url: "/hackthebox"
          parent: "writeups"
        - identifier: "tools"
          name: "Tools"
          url: "/tools"
          parent: "tools and resources"
        - identifier: "useful"
          name: "Resources"
          parent: "tools and resources"          
